version: "3"

services:
  db:
    build:
      context: .
      dockerfile: dockerfiles/postgres/Dockerfile
    image: dal-postgres
    container_name: dal-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres12345
      - PGPASSWORD=postgres12345
      - POSTGRES_DB=jedi_db
      - DATABASE_HOST=localhost
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/work/data:/tmp/data

  notebook:
    build:
      context: .
      dockerfile: dockerfiles/notebook/Dockerfile
    image: dal-notebook
    container_name: dal-notebook
    ports:
      - "8890:8888"
    environment:
      - PG_PORT=5432
      - PG_USER=jedi
      - PG_PASSWORD=jedi12345
      - PG_DATABASE=jedi_db
      - JUPYTER_ENABLE_LAB=no
    links:
      - db
    volumes:
      - ./docker/doc:/home/jovyan/doc
      - ./docker/work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
